ORG_NAME=org1
CA_PEER_PORT=2054
CA_ORDERER_PORT=3054
PEER1_NAME=peer0
PEER2_NAME=peer1
ORDERER1_NAME=orderer0
ORDERER2_NAME=orderer1 # orderer가 1개인 경우 삭제
ORDERER_ORG=OrdererOrg1
PEER_ORG=PeerOrg1
PEER1_PORT=2051
PEER2_PORT=3051
ORDERER1_PORT=2050
ORDERER2_PORT=3050 # orderer가 1개인 경우 삭제

export ORG_NAME 
export CA_PEER_PORT CA_ORDERER_PORT 
export PEER1_NAME PEER2_NAME 
export ORDERER1_NAME ORDERER2_NAME
export ORDERER_ORG PEER_ORG
export PEER1_PORT PEER2_PORT
export ORDERER1_PORT ORDERER2_PORT


