# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: '2'

networks:
  test:

services:
  couchdb0:
    container_name: ${PEER1_COUCHDB_NAME}
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "${COUCHDB0_PORT}:5984"
    networks:
      - test

  couchdb1:
    container_name: ${PEER2_COUCHDB_NAME}
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "${COUCHDB1_PORT}:5984"
    networks:
      - test